CREATE TABLE raimed_diagnostic
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    UUID                                    NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status VARCHAR(255)                                NOT NULL,
    CONSTRAINT pk_raimed_diagnostic PRIMARY KEY (id)
);

ALTER TABLE raimed_diagnostic
    ADD CONSTRAINT FK_RAIMED_DIAGNOSTIC_ON_USER FOREIGN KEY (user_id) REFERENCES raimed_user (id);