CREATE TABLE raimed_prescription
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255)                            NOT NULL,
    content VARCHAR(255)                            NOT NULL,
    result  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_raimed_prescription PRIMARY KEY (id)
);

ALTER TABLE raimed_action
    ADD COLUMN prescription_id BIGINT;

ALTER TABLE raimed_action
    ADD CONSTRAINT FK_RAIMED_ACTION_ON_PRESCRIPTION FOREIGN KEY (prescription_id) REFERENCES raimed_prescription (id);