CREATE TABLE raimed_virtual_patient
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    age INTEGER NOT NULL,
    gender VARCHAR(255) NOT NULL,
    result VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by UUID,
    CONSTRAINT pk_raimed_virtual_patient PRIMARY KEY (id)
);

ALTER TABLE raimed_diagnostic
    ADD virtual_patient_id BIGINT;

ALTER TABLE raimed_diagnostic
    ALTER COLUMN virtual_patient_id SET NOT NULL;

ALTER TABLE raimed_diagnostic
    ADD CONSTRAINT FK_RAIMED_DIAGNOSTIC_ON_VIRTUAL_PATIENT FOREIGN KEY (virtual_patient_id) REFERENCES raimed_virtual_patient (id);

ALTER TABLE raimed_virtual_patient
    ADD CONSTRAINT FK_RAIMED_VIRTUAL_PATIENT_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES raimed_user (id);