CREATE TABLE raimed_symptome
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question VARCHAR(255)                            NOT NULL,
    answer  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_raimed_symptome PRIMARY KEY (id)
);

ALTER TABLE raimed_action
    ADD COLUMN symptome_id BIGINT;

ALTER TABLE raimed_action
    ADD CONSTRAINT FK_RAIMED_ACTION_ON_SYMPTOME FOREIGN KEY (symptome_id) REFERENCES raimed_symptome (id);