CREATE TABLE raimed_question
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255)                            NOT NULL,
    content VARCHAR(255)                            NOT NULL,
    filter  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_raimed_question PRIMARY KEY (id)
);

ALTER TABLE raimed_question
    ADD CONSTRAINT uc_raimed_question_content UNIQUE (content);