CREATE TABLE raimed_precision
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question VARCHAR(255)                            NOT NULL,
    answer  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_raimed_precision PRIMARY KEY (id)
);

ALTER TABLE raimed_action
    ADD COLUMN precision_id BIGINT;

ALTER TABLE raimed_action
    ADD CONSTRAINT FK_RAIMED_ACTION_ON_PRECISION FOREIGN KEY (precision_id) REFERENCES raimed_precision (id);