CREATE TABLE raimed_prescription
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type    VARCHAR(255)                            NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    result  VARCHAR(255)                            ,
    is_mutual BOOLEAN,
    teacher_id UUID,
    CONSTRAINT pk_raimed_prescription PRIMARY KEY (id)
);

ALTER TABLE raimed_prescription
    ADD CONSTRAINT uc_raimed_prescription_content UNIQUE (name);

-- Set automatique de is_mutual si teacher_id != null
CREATE OR REPLACE FUNCTION set_is_mutual()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.teacher_id IS NULL THEN
        NEW.is_mutual := TRUE;
ELSE
        NEW.is_mutual := FALSE;
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Création du trigger
CREATE TRIGGER trg_set_is_mutual_prescription
    BEFORE INSERT OR UPDATE ON raimed_prescription
                         FOR EACH ROW
                         EXECUTE FUNCTION set_is_mutual();