import type { ExamType } from '@/models/exam/examType.enum';

export enum Zones {
  SKIN = 'SKIN',
  FACE = 'FACE',
  MOUSE = 'MOUSE',
  EYES = 'EYES',
  EARS = 'EARS',
  SHOULDERS = 'SHOULDERS',
  ARMS = 'ARMS',
  CHEST = 'CHEST',
  ABDOMEN = 'ABDOMEN',
  GENITALS = 'GENITALS',
  PERINEUM = 'PERINEUM',
  HANDS = 'HANDS',
  LEGS = 'LEGS',
  HAIRS = 'HAIRS',
  NECK = 'NECK',
  BACK = 'BACK',
  ELBOWS = 'ELBOWS',
  FEET = 'FEET',
  MEMBERS = 'MEMBERS'
}

export const ZoneDisplayNames: Record<Zones, string> = {
  [Zones.SKIN]: 'Peau',
  [Zones.FACE]: 'Visage',
  [Zones.MOUSE]: 'Bouche',
  [Zones.EYES]: 'Yeux',
  [Zones.EARS]: 'Conduits auditifs',
  [Zones.SHOULDERS]: 'Épaules',
  [Zones.ARMS]: 'Bras',
  [Zones.CHEST]: 'Thorax',
  [Zones.ABDOMEN]: 'Abdomen',
  [Zones.GENITALS]: 'Organes génitaux',
  [Zones.PERINEUM]: 'Périné',
  [Zones.HANDS]: 'Mains',
  [Zones.LEGS]: 'Jambes',
  [Zones.HAIRS]: 'Cheveux',
  [Zones.NECK]: 'Cou',
  [Zones.BACK]: 'Dos',
  [Zones.ELBOWS]: 'Coudes',
  [Zones.FEET]: 'Pieds',
  [Zones.MEMBERS]: 'Membres'
};

export const AuscultationSigns = {
  [Zones.CHEST]: [
    'Abolition ou diminution du murmure vésivulaire (auscultation pulmonaire)',
    'Crépitants, ronchis ou sibilants (auscultation pulmonaire)',
    'Frottement pleural (auscultation pulmonaire)',
    'Souffle tubaire (auscultation pulmonaire)'
  ],
  [Zones.ABDOMEN]: [
    'Abolition ou diminution des bruits hydro-aériques (auscultation digestive)'
  ],
  [Zones.EARS]: [
    'Stridor inspiratoire (auscultation ORL)'
  ]
};

export const InspectionSigns = {
  [Zones.SKIN]: [
    'Acanthosis nigricans',
    'Angiome plan',
    'Angiome rubis',
    'Angiomes stellaires',
    'Anhydrose',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Cyanose',
    'Décollement épidermique',
    'Dépilation',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Erythrose faciale',
    'Escarre',
    'Folliculite',
    'Furoncle',
    'Hématome',
    'Hirsutisme',
    'Hyperhydrose',
    'Hypertrichose',
    'Ictère',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Paleur cutanée',
    'Papule érythémateuse',
    'Phototype 1',
    'Plaque cutanée',
    'Poliose',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Verrue',
    'Vésicules',
    'Vitiligo',
    'Xanthélasma',
    'Xanthome'
  ],
  [Zones.HAIRS]: [
    'Alopécie diffuse',
    'Alopécie localisée',
    'Angiome plan',
    'Angiome rubis',
    'Aucune anomalie',
    'Canitie',
    'Erosion',
    'Erythème',
    'Erythrodermie',
    'Folliculite',
    'Furoncle',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Naevus',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Pustules',
    'Tache café au lait',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Vésicules'
  ],
  [Zones.FACE]: [
    'Angiome plan',
    'Anhydrose',
    'Asymétrie du visage',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Dépilation',
    'Déviation de la cloison nasale',
    'Dysmorphie du visage',
    'Ensellure nasale',
    'Ephélides',
    'Epicanthus',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Erythrose faciale',
    'Exophtalmie bilatérale',
    'Exophtalmie unilatérale',
    'Faciès lunaire',
    'Folliculite',
    'Furoncle',
    'Goitre',
    'Hématome',
    'Hirsutisme',
    'Hyperhydrose',
    'Hypertrichose',
    'Hypertrophie glandes lacrymales',
    'Hypertrophie glandes sous-mandibulaires',
    'Hypertrophie parotidienne bilatérale',
    'Hypertrophie parotidienne unilatérale',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Mélanodermie',
    'Naevus',
    'Nodule cutané',
    'Papule érythémateuse',
    'Perforation de la cloison nasale',
    'Perlèche',
    'Plaque cutanée',
    'Plis radiés péri-buccaux',
    'Polype nasal',
    'Ptosis',
    'Purpura pétéchial',
    'Pustules',
    'Rhinorrhée',
    'Sclérose cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tirage',
    'Tuméfaction',
    'Tumeur cutanée',
    'Turgescence jugulaire',
    'Ulcération',
    'Urticaire',
    'Vésicules',
    'Vitiligo',
    'Xanthélasma'
  ],
  [Zones.MOUSE]: [
    'Aphte',
    'Aucune anomalie',
    'Bulles',
    'Bulles hémorragiques intra-buccales',
    'Chancre',
    'Chéilite',
    'Erosion',
    'Erythème',
    'Erythème pharyngé',
    'Fente palatine',
    'Glossite',
    'Langue dépapillée',
    'Leucoplasie',
    'Macroglossie',
    'Macule érythémateuse',
    'Mélanodermie',
    'Papule érythémateuse',
    'Perlèche',
    'Plis radiés péri-buccaux',
    'Purpura du voile du palais',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Sillon lingual médian',
    'Stomatite',
    'Taches de Koplik',
    'Télangiectasies',
    'Tuméfaction',
    'Ulcération',
    'Ulcération buccale',
    'Vésicules'
  ],
  [Zones.EARS]: [
    'Aucune anomalie',
    'Cérumen',
    'Corps étranger dans le conduit auditif externe',
    'Erosion',
    'Erythème',
    'Hématome',
    'Otorragie',
    'Otorrhée',
    'Tuméfaction',
    'Tympan bombant jaunatre',
    'Ulcération',
    'Vésicules'
  ],
  [Zones.EYES]: [
    'Anisocorie',
    'Arc cornéen',
    'Aucune anomalie',
    'Epicanthus',
    'Erythème conjonctival',
    'Exophtalmie bilatérale',
    'Exophtalmie unilatérale',
    'Hémorragie sous-conjonctivale',
    'Hypertrophie glandes lacrymales',
    'Mydriase',
    'Myosis',
    'Paleur conjonctivale',
    'Ptosis',
    'Subictère',
    'Ulcération',
    'Xanthélasma'
  ],
  [Zones.HANDS]: [
    'Aucune anomalie',
    'Bulles',
    'Cor au pied',
    'Coup de vent ulnaire',
    'Cyanose',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dermite ocre',
    'Doigts en boutonnière',
    'Doigts en col de cygne',
    'Dysmorphie des extrémitées',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème palmaire',
    'Erythrodermie',
    'Escarre',
    'Gonflement articulaire',
    'Hallux valgux',
    'Hématome',
    'Hemorragies sous-unguéales',
    'Hippocratisme digital',
    'Hirsutisme',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Koïlonychie',
    'Leuconychie',
    'Lignes de Beau',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Mélanodermie',
    'Mélanonychie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Ongle incarné',
    'Ongles cassants',
    'Ongles en dés à coudre',
    'Onycholyse',
    'Papule érythémateuse',
    'Périonyxis',
    'Pied creux',
    'Pied plat',
    'Plaque cutanée',
    'Polydactylie',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Syndactylie',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Verrue',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.FEET]: [
    'Aucune anomalie',
    'Bulles',
    'Cor au pied',
    'Coup de vent ulnaire',
    'Cyanose',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dermite ocre',
    'Doigts en boutonnière',
    'Doigts en col de cygne',
    'Dysmorphie des extrémitées',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème palmaire',
    'Erythrodermie',
    'Escarre',
    'Gonflement articulaire',
    'Hallux valgux',
    'Hématome',
    'Hemorragies sous-unguéales',
    'Hippocratisme digital',
    'Hirsutisme',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Koïlonychie',
    'Leuconychie',
    'Lignes de Beau',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Mélanodermie',
    'Mélanonychie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Ongle incarné',
    'Ongles cassants',
    'Ongles en dés à coudre',
    'Onycholyse',
    'Papule érythémateuse',
    'Périonyxis',
    'Pied creux',
    'Pied plat',
    'Plaque cutanée',
    'Polydactylie',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Syndactylie',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Verrue',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.ARMS]: [
    'Amyotrophie',
    'Angiome plan',
    'Angiome rubis',
    'Atrophie blanche',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dépilation',
    'Dermite ocre',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Fasciculations musculaires',
    'Flessum articulaire',
    'Folliculite',
    'Furoncle',
    'Gonflement articulaire',
    'Hématome',
    'Hirsutisme',
    'Hypertrichose',
    'Hypertrophie musculaire',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Œdème du membre inférieur droit',
    'Œdème du membre inférieur gauche',
    'Oedèmes bilatéraux des membres inférieurs',
    'Oedèmes bilatéraux des membres supérieurs',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Varices',
    'Varicosités',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.LEGS]: [
    'Amyotrophie',
    'Angiome plan',
    'Angiome rubis',
    'Atrophie blanche',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dépilation',
    'Dermite ocre',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Fasciculations musculaires',
    'Flessum articulaire',
    'Folliculite',
    'Furoncle',
    'Gonflement articulaire',
    'Hématome',
    'Hirsutisme',
    'Hypertrichose',
    'Hypertrophie musculaire',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Œdème du membre inférieur droit',
    'Œdème du membre inférieur gauche',
    'Oedèmes bilatéraux des membres inférieurs',
    'Oedèmes bilatéraux des membres supérieurs',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Varices',
    'Varicosités',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.ELBOWS]: [
    'Amyotrophie',
    'Angiome plan',
    'Angiome rubis',
    'Atrophie blanche',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dépilation',
    'Dermite ocre',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Fasciculations musculaires',
    'Flessum articulaire',
    'Folliculite',
    'Furoncle',
    'Gonflement articulaire',
    'Hématome',
    'Hirsutisme',
    'Hypertrichose',
    'Hypertrophie musculaire',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Œdème du membre inférieur droit',
    'Œdème du membre inférieur gauche',
    'Oedèmes bilatéraux des membres inférieurs',
    'Oedèmes bilatéraux des membres supérieurs',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Varices',
    'Varicosités',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.MEMBERS]: [
    'Amyotrophie',
    'Angiome plan',
    'Angiome rubis',
    'Atrophie blanche',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dépilation',
    'Dermite ocre',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Fasciculations musculaires',
    'Flessum articulaire',
    'Folliculite',
    'Furoncle',
    'Gonflement articulaire',
    'Hématome',
    'Hirsutisme',
    'Hypertrichose',
    'Hypertrophie musculaire',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Œdème du membre inférieur droit',
    'Œdème du membre inférieur gauche',
    'Oedèmes bilatéraux des membres inférieurs',
    'Oedèmes bilatéraux des membres supérieurs',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Varices',
    'Varicosités',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.SHOULDERS]: [
    'Amyotrophie',
    'Angiome plan',
    'Angiome rubis',
    'Atrophie blanche',
    'Aucune anomalie',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Décollement épidermique',
    'Déformation d\'un membre',
    'Déformation articulaire',
    'Dépilation',
    'Dermite ocre',
    'Echymoses',
    'Ephélides',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Fasciculations musculaires',
    'Flessum articulaire',
    'Folliculite',
    'Furoncle',
    'Gonflement articulaire',
    'Hématome',
    'Hirsutisme',
    'Hypertrichose',
    'Hypertrophie musculaire',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Marbrures',
    'Mélanodermie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Nouure cutanée',
    'Œdème du membre inférieur droit',
    'Œdème du membre inférieur gauche',
    'Oedèmes bilatéraux des membres inférieurs',
    'Oedèmes bilatéraux des membres supérieurs',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Sécheresse cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tremblement d\'action',
    'Tremblement de repos',
    'Tremblement d\'intention',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Ulcère creusant',
    'Ulcère superficiel',
    'Urticaire',
    'Varices',
    'Varicosités',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.CHEST]: [
    'Angiome plan',
    'Angiome rubis',
    'Angiomes stellaires',
    'Aucune anomalie',
    'Balancement thoraco-abdominal',
    'Bradypnée',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Circulation veineuse collatérale thoracique',
    'Décollement épidermique',
    'Echymoses',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Folliculite',
    'Furoncle',
    'Goitre',
    'Gynecomastie',
    'Hématome',
    'Hirsutisme',
    'Hyperhydrose',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Naevus',
    'Nodule cutané',
    'Orthopnée',
    'Papule érythémateuse',
    'Pectus carinatum',
    'Pectus excavatum',
    'Plaque cutanée',
    'Polypnée',
    'Purpura ecchymotique',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Respiration de Cheynes-Stokes',
    'Respiration de Kussmaul',
    'Rétraction mamelonnaire',
    'Sclérose cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tirage',
    'Tuméfaction',
    'Tumeur cutanée',
    'Turgescence jugulaire',
    'Ulcération',
    'Urticaire',
    'Vésicules',
    'Vitiligo'
  ],
  [Zones.ABDOMEN]: [
    'Abdomen distendu',
    'Angiome plan',
    'Angiome rubis',
    'Ascite visible',
    'Aucune anomalie',
    'Balancement thoraco-abdominal',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Circulation veineuse collatérale abdominale',
    'Décollement épidermique',
    'Echymoses',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Eventration',
    'Folliculite',
    'Furoncle',
    'Hématome',
    'Hernie inguinale',
    'Hernie ombilicale',
    'Hirsutisme',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Naevus',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Tache café au lait',
    'Télangiectasies',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Urines décolorées',
    'Urines foncées',
    'Urines rouges',
    'Urines troubles',
    'Urticaire',
    'Vésicules',
    'Vitiligo'
  ],
  [Zones.BACK]: [
    'Angiome plan',
    'Angiome rubis',
    'Angiomes stellaires',
    'Aucune anomalie',
    'Bosse de bison',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Cyphose dorsale',
    'Décollement épidermique',
    'Echymoses',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Escarre',
    'Folliculite',
    'Furoncle',
    'Goitre',
    'Hématome',
    'Hirsutisme',
    'Hyperhydrose',
    'Hyperlordose lombaire',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Naevus',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Scoliose',
    'Tache café au lait',
    'Télangiectasies',
    'Tirage',
    'Tuméfaction',
    'Tumeur cutanée',
    'Turgescence jugulaire',
    'Ulcération',
    'Urticaire',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.NECK]: [
    'Angiome plan',
    'Angiome rubis',
    'Angiomes stellaires',
    'Aucune anomalie',
    'Bosse de bison',
    'Bulles',
    'Cicatrice chéloïde',
    'Cicatrices chirurgicales',
    'Cyphose dorsale',
    'Décollement épidermique',
    'Echymoses',
    'Erosion',
    'Erythème',
    'Erythème morbiliforme',
    'Erythème roséoliforme',
    'Erythème scarlatiniforme',
    'Erythrodermie',
    'Escarre',
    'Folliculite',
    'Furoncle',
    'Goitre',
    'Hématome',
    'Hirsutisme',
    'Hyperhydrose',
    'Hyperlordose lombaire',
    'Hypertrichose',
    'Kératose',
    'Kératose actinique',
    'Kératose séborhéique',
    'Livedo',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Naevus',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Purpura ecchymotique',
    'Purpura en vibices',
    'Purpura nécrotique',
    'Purpura pétéchial',
    'Pustules',
    'Sclérose cutanée',
    'Scoliose',
    'Tache café au lait',
    'Télangiectasies',
    'Tirage',
    'Tuméfaction',
    'Tumeur cutanée',
    'Turgescence jugulaire',
    'Ulcération',
    'Urticaire',
    'Vésicules',
    'Vitiligo',
    'Xanthome'
  ],
  [Zones.GENITALS]: [
    'Aucune anomalie',
    'Chancre',
    'Cryptorchidie',
    'Dépilation',
    'Erosion',
    'Erythème',
    'Erythrodermie',
    'Escarre',
    'Folliculite',
    'Furoncle',
    'Hernie inguinale',
    'Hirsutisme',
    'Hypertrichose',
    'Kératose',
    'Macroorchidie',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Microorchidie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Prolapsus rectal',
    'Prolapsus utérin',
    'Pustules',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Vésicules',
    'Vitiligo'
  ],
  [Zones.PERINEUM]: [
    'Aucune anomalie',
    'Chancre',
    'Cryptorchidie',
    'Dépilation',
    'Erosion',
    'Erythème',
    'Erythrodermie',
    'Escarre',
    'Folliculite',
    'Furoncle',
    'Hernie inguinale',
    'Hirsutisme',
    'Hypertrichose',
    'Kératose',
    'Macroorchidie',
    'Macule achromique',
    'Macule érythémateuse',
    'Macule pigmentée',
    'Microorchidie',
    'Naevus',
    'Nécrose',
    'Nodule cutané',
    'Papule érythémateuse',
    'Plaque cutanée',
    'Prolapsus rectal',
    'Prolapsus utérin',
    'Pustules',
    'Tuméfaction',
    'Tumeur cutanée',
    'Ulcération',
    'Vésicules',
    'Vitiligo'
  ]
};

export const PalpationSigns = {
  [Zones.ABDOMEN]: [
    'Abdomen distendu',
    'Contracture abdominale',
    'Défense abdominale',
    'Douleur à la palpation abdominale',
    'Douleur au point de McBurney',
    'Eventration',
    'Fécalome',
    'Hémorroïdes externes',
    'Hémorroïdes internes',
    'Hépatomégalie',
    'Hernie crurale',
    'Hernie inguinale',
    'Hernie ombilicale',
    'Masse digestive/abdominale palpable',
    'Masse dure de la paroi rectale au TR',
    'Matité abdominale et signe du flot / Ascite',
    'Melena au TR',
    'Rectorragie au TR',
    'Signe de Murphy',
    'Splénomégalie'
  ],
  [Zones.CHEST]: [
    'Absence d\'un pouls périphérique',
    'Cordon veineux induré',
    'Cyanose ou pléthore faciale à l\'élévation des membres supérieurs',
    'Douleur à la pression et l\'extension du mollet',
    'Masse abdominale pulsatile',
    'Membre ou extrémité froide',
    'Œdème des membres inférieurs prenant le godet',
    'Œdème des membres inférieurs sans godet',
    'Reflux hépato-jugulaire',
    'Thrill cardiaque',
    'Thrill d\'une fistule artério-veineuse',
    'Diminution des vibrations vocales',
    'Douleur pariétale à la pression sur le thorax',
    'Anomalie au test d\'Allen',
    'Disparition du pouls à la manœuvre d\'Adson'
  ],
  [Zones.EARS]: [
    'Douleur à la pression des sinus',
    'Douleur aux sinus en antéflexion',
    'Test de Rinne anormal',
    'Test de Weber anormal'
  ],
  [Zones.FACE]: [
    'Abolition d\'un ou plusieurs ROT',
    'Allodynie',
    'Déficit de contraction du sphincter anal',
    'Déficit moteur du visage',
    'Déficit moteur des membres inférieurs',
    'Déficit moteur des membres supérieurs',
    'Déficit sensitif périnéal',
    'Déficit sensitif d\'un membre',
    'Déficit sensitif du visage',
    'Déficit des mouvements oculo-moteurs',
    'Déviation de la langue',
    'Douleur faciale à l\'effleurement',
    'Dysmétrie à l\'épreuve doigt-nez',
    'Dysmétrie à l\'épreuve talon-genou',
    'Trouble sensibilité plantaire',
    'Hémianopsie ou quadranopsie',
    'Hyperesthésie',
    'Hyperréflexie',
    'Hypertonie plastique',
    'Hypertonie spastique',
    'Hypopallesthésie',
    'Marche sur les talons ou pointes impossible',
    'ROT achilléen aboli',
    'ROT bicipital aboli',
    'ROT rotulien aboli',
    'ROT stylo-radial aboli',
    'ROT tricipital aboli',
    'Signe de Babinski',
    'Signe de Brudzinski',
    'Signe de Froment',
    'Signe de Hoffman',
    'Signe de Kernig',
    'Signe de Lhermitte',
    'Signe de Romberg',
    'Signe de Trousseau',
    'Trouble proprioceptif',
    'Adiadococinésie au test des marionnettes'
  ],
  [Zones.GENITALS]: [
    'Chaleur cutanée mammaire',
    'Douleur au TV',
    'Douleur mammaire à la pression',
    'Masse pelvienne au TV',
    'Masse/Nodule mammaire',
    'Douleur prostatique au TR',
    'Masse/nodule épididymaire',
    'Varicocèle',
    'Ascension d\'un testicule',
    'Augmentation de volume d\'un testicule',
    'Douleur testiculaire',
    'Masse/nodule testiculaire',
    'Signe de Prehn'
  ],
  [Zones.HANDS]: [
    'Absence de flexion plantaire du pied',
    'Chaleur articulaire',
    'Diminution de la mobilité articulaire',
    'Douleur à la mobilisation articulaire',
    'Douleur à la pression des enthèses',
    'Douleur osseuse',
    'Douleur vertébrale',
    'Douleur sacro-iliaque',
    'Épanchement articulaire',
    'Flessum',
    'Hyperlaxité ligamentaire',
    'Induration des artères temporales',
    'Instabilité ligamentaire du genou',
    'Myalgie à la contraction',
    'Myalgie à la pression',
    'Raideur rachidienne cervicale',
    'Raideur rachidienne thoracique',
    'Signe de Lasègue',
    'Signe de Léri',
    'Signe de Phalen',
    'Signe de Tietze',
    'Signe du peigne',
    'Signe du rabot',
    'Douleur à la manœuvre de Hawkins',
    'Douleur à la manœuvre de Neer',
    'Douleur à la manœuvre de Yocum',
    'Douleur ou déficit à la manœuvre de Patte',
    'Douleur ou déficit au belly press test',
    'Douleur ou déficit au lift off test',
    'Douleur ou déficit au palm-up test',
    'Douleur ou déficit au test de Jobe',
    'Raideur rachidienne lombaire / Test de Schober',
    'Test d’Apley',
    'Test de McMurray'
  ],
  [Zones.LEGS]: ['Test de Lachman', 'Tiroir antérieur', 'Tiroir postérieur'],
  [Zones.NECK]: [
    'Douleur thyroïdienne',
    'Masse/nodule thyroïdien',
    'Adénopathies axillaires',
    'Adénopathies cervicales',
    'Adénopathies inguinales'
  ],
  [Zones.SKIN]: [
    'Chaleur cutanée',
    'Crépitations sous-cutanées',
    'Douleur cutanée',
    'Durillon plantaire',
    'Masse/Nodule sous-cutané',
    'Purpura palpable',
    'Sclérose cutanée distale',
    'Sclérose cutanée localisée'
  ],
};

export const PercussionSigns = {
  [Zones.ABDOMEN]: [
    'Tympanisme à la percussion pré-hépatique',
    'Tympanisme diffus à la percussion abdominale'
  ],
  [Zones.CHEST]: ['Matité à la percussion thoracique', 'Tympanisme à la percussion pulmonaire'],
  [Zones.FACE]: ['Signe de Chvostek'],
  [Zones.GENITALS]: ['Douleur à la percussion lombaire'],
  [Zones.HANDS]: ['Signe de Tinel'],
};

export interface ExamResults {
  id?: string;
  zone: Zones;
  signs: string[];
  type?: ExamType;
}
