name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        working-directory: ./raimed2Back

      - name: Run unit tests (excluding integration tests)
        run: mvn test -Dtest='!fr.imt.raimed2.integration.**.*'
        working-directory: ./raimed2Back

      - name: Run UserIntegrationTest
        run: mvn -B test -Dtest='fr.imt.raimed2.integration.**.*'
        working-directory: ./raimed2Back

      - name: Run AuthenticationIntegrationTest
        run: mvn -B test -Dtest='fr.imt.raimed2.integration.authentication.AuthenticationIntegrationTest'
        working-directory: ./raimed2Back

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./raimed2Back/target/site/jacoco/jacoco.xml
